Origin/feature/eventos
gbrlCM/MC4-Capivara-Gamer pull request #6
Opened 2021-12-03 19:16 UTC by thallissousa

### Qual é o propósito desse Pull Request?
Página e Eventos finalizada.

### O que foi alterado?
Lógica da página de eventos criada e alimentada por um Mock. 

### O que isso vai trazer em resultados?
Possibilita a continuação do aplicativo e a implementação do backend.

2021-12-03 21:00 UTC, gbrlCM requested changes

2021-12-03 21:00 UTC, gbrlCM commented on Capivara/Screen/MyEvents/Views/EventCardView.swift
> +//                        .frame(width: 30, height: 30)
Coding comentario

2021-12-03 21:02 UTC, thallissousa commented on Capivara/Screen/MyEvents/Views/EventCardView.swift
> +//                        .frame(width: 30, height: 30)
Alterado!

2021-12-06 16:37 UTC, NathyPapst approved these changes

2021-12-06 16:39 UTC, gbrlCM approved these changes

2021-12-06 16:54 UTC, merged